version: '3.7'

services:
  app-server:
    build:
      context: backendApp 
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    restart: always
    networks:
      - backend_frontend
 
  app-frontend:
    build:
      context: frontend  
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080/api/file-store/upload/
    ports:
      - "9090:80"
    restart: always
    depends_on:
      - app-server
    networks:
      - backend_frontend

networks:
  backend_frontend:
